version: '3.4'

services:
  acmeordersystem.api:
    image: ${DOCKER_REGISTRY-}acmeordersystemapi
    container_name: acmeordersystem.api
    build:
      context: .
      dockerfile: AcmeOrderSystem.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"

  acmeordersystem.database:
    image: postgres:latest
    container_name: acmeordersystem.database
    environment:
      - POSTGRES_DB=AcmeOrderSystem
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/AcmeOrderSystem-db:/var/lib/postgresql/data
    ports:
      - 5432:5432